name: anvugib-rebleeding
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas=2.2.2
  - numpy=1.26.4
  - scikit-learn=1.5.0
  - statsmodels=0.14.1
  - matplotlib=3.8.4
  - joblib=1.4.2
